# Generated by Django 4.1.4 on 2023-04-23 15:29

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='galleryimages/')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=150)),
                ('rate_per_night', models.PositiveIntegerField()),
                ('size', models.CharField(max_length=150)),
                ('capacity', models.CharField(max_length=150)),
                ('bed', models.CharField(max_length=150)),
                ('services', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='roomimages/')),
                ('discriptions', ckeditor.fields.RichTextField()),
                ('room_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='room_name', unique=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RoomRelatedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='roomimages/')),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_details', to='app.room')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
