# Generated by Django 4.1.4 on 2023-04-23 16:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_gallery_room_roomrelatedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('discriptions', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-id'],
            },
        ),
    ]
