# Generated by Django 4.1.4 on 2023-04-23 16:43

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
                ('category_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='category_name', unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=150)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='blogimages/')),
                ('discriptions', ckeditor.fields.RichTextField()),
                ('blog_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='blog_title', unique=True)),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_category', to='app.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-id'],
            },
        ),
    ]
