# Generated by Django 4.1.4 on 2023-04-24 09:19

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_blogcategory_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=150)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='packageimages/')),
                ('rate', models.PositiveIntegerField()),
                ('discriptions', ckeditor.fields.RichTextField()),
                ('package_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='package_name', unique=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['-id'],
            },
        ),
    ]
