# Generated by Django 4.1.4 on 2023-04-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_frequentlyaskedquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequentlyaskedquestion',
            options={'ordering': ['id'], 'verbose_name': 'Frequently Asked Question', 'verbose_name_plural': 'Frequently Asked Questions'},
        ),
    ]
