# Generated by Django 4.1.4 on 2023-04-24 15:07

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_locality_locality_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aminities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aminities_name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='aminitiesimage/')),
                ('discriptions', ckeditor.fields.RichTextField()),
                ('aminitie_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='aminities_name', unique=True)),
            ],
            options={
                'verbose_name': 'Aminities',
                'verbose_name_plural': 'Aminities',
                'ordering': ['-id'],
            },
        ),
    ]
